name: walk_for_wealth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  another_flushbar: ^1.12.30
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5
  dio: ^5.6.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.1.1
  fpdart: ^1.1.0
  geolocator: ^13.0.1
  get_it: ^7.7.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  wheel_chooser: ^1.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
